# Build and run containers
# docker-compose up --build -d

# List containers
# docker ps

# Stop and remove containers
# docker-compose down

# Remove all images
# docker rmi -f $(docker images -aq)

services:
    gateway:
        depends_on:
            - api
            - angular
        build:
            context: ./apps/gateway
            dockerfile: Dockerfile
        restart: always # because it is routing traffic to our entire app
        container_name: word-finder-gateway
        ports:
            - '80:80'
        expose:
            - 80

    api:
        build:
            context: ./apps/word-list-api
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        volumes:
            - .:/code
        restart: on-failure
        container_name: word-list-api
        environment:
            - ACCESS_TOKEN=${ACCESS_TOKEN}

    angular:
        build:
            context: ./apps/word-finder-ui
            dockerfile: Dockerfile
            args:
                - ACCESS_TOKEN=${ACCESS_TOKEN}
        container_name: word-finder-ui
        ports:
            - 3000:3000
