# Build and run containers
# docker compose up --build -d

# List containers
# docker ps

# Stop and remove containers
# docker compose down

# Remove all images
# docker rmi -f $(docker images -aq)

# Stop all the containers
# docker stop $(docker ps -a -q)

# Remove all the containers
# docker rm $(docker ps -a -q)

services:
    api:
        image: 'marshallgraphics/word-finder-api:latest'
        build:
            context: ./apps/word-list-api
            dockerfile: Dockerfile
        container_name: word-finder-api
        restart: on-failure
        ports:
            - '3000:3000'
        volumes:
            - .:/code

    ui:
        image: 'marshallgraphics/word-finder-ui:latest'
        build:
            context: ./apps/word-finder-ui
            dockerfile: Dockerfile
        container_name: word-finder-ui
        restart: always # because it is routing traffic to our entire app
        depends_on:
            - api
        ports:
            - '80:80'
        expose:
            - 80
