# Build and run containers
# docker-compose up --build -d

# List containers
# docker ps

# Stop and remove containers
# docker-compose down

services:
    word-finder:
        build:
            context: .
            args:
                - ACCESS_TOKEN=${ACCESS_TOKEN}
        image: word-finder:v1
        ports:
            - 80:3000
        expose:
            - 80
