name: Deploy To Digital Ocean

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    #   uses: actions/checkout@v1
    # - name: Deploy static site to S3 bucket
    #   run: aws s3 sync ./dist <BUCKET DESTINATION>

    - name: ssh-run
      uses: nekiro/ssh-job@main
      with:
        host: ${{ vars.DO_SSH_HOST }}
        key: ${{ secrets.DO_SSH_KEY }}
        user: ${{ secrets.DO_SSH_USER }}
        envs: ${{ toJson(secrets) }}
        command: |
          cd ${{ vars.DO_APP_PATH }}
          git pull
          echo 'ACCESS_TOKEN=$APP_ACCESS_TOKEN' > .env
          docker compose down
          docker rmi -f $(docker images -aq)
          docker compose up --build -d
          exit
